/* ==== Test Created with Cypress Studio ==== */
it('generationTest', function() {
  /* ==== Generated with Cypress Studio ==== */
  cy.visit('http://10.18.0.14:3001/#/events/configure');
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').clear();
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').type('swintern');
  cy.get(':nth-child(2) > .el-form-item__content > .el-input > .el-input__inner').clear();
  cy.get(':nth-child(2) > .el-form-item__content > .el-input > .el-input__inner').type('Clounix123');
  cy.get('.el-button').click();
  cy.get('.container-notification').click();
  cy.get(':nth-child(3) > .select-trigger > .el-input > .el-input__suffix > .el-input__suffix-inner > .el-icon > svg').click();
  cy.get('[aria-hidden="false"] > .el-select-dropdown > .el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(1)').click();
  cy.get(':nth-child(5) > .select-trigger > .el-input > .el-input__inner').click();
  cy.get('[aria-hidden="false"] > .el-select-dropdown > .el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(1)').click();
  cy.get(':nth-child(7) > .select-trigger > .el-input > .el-input__inner').click();
  cy.get('[aria-hidden="false"] > .el-select-dropdown > .el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(1)').click();
  cy.get('.con-container > article > :nth-child(2)').click();
  cy.get('article > :nth-child(3)').click();
  cy.get('article > :nth-child(4)').click();
  cy.get('.con-container > article > :nth-child(2)').click();
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').click();
  cy.get(':nth-child(2) > .el-form-item__content > .el-input > .el-input__inner').click();
  cy.get(':nth-child(3) > .el-form-item__content > .el-input > .el-input__inner').click();
  cy.get('.el-switch__action').click();
  cy.get(':nth-child(5) > .el-form-item__content > .el-input > .el-input__inner').click();
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').clear();
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').type('smtp.clounix.com');
  // cy.get('.is-error > .el-form-item__label').click();
  cy.get('#lang > :nth-child(3)').click();
  cy.get('#lang > :nth-child(1)').click();
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').click();
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').clear();
  cy.get(':nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').type('smtp.clounix.com');
  cy.get('.el-form > .el-button > .el-icon > svg').click();
  cy.get('article > :nth-child(3)').click();
  // cy.get(':nth-child(1) > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').click();
  // cy.get(':nth-child(1) > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').click();
  // cy.get(':nth-child(1) > :nth-child(2) > .el-form-item__content > .el-input > .el-input__inner').click();
  // cy.get(':nth-child(1) > :nth-child(1) > .el-button').click();
  // cy.get('[aria-hidden="false"] > div > .el-button--primary > span').click();
  // cy.get(':nth-child(1) > :nth-child(1) > .el-button').click();
  // cy.get('[aria-hidden="false"] > div > .el-button--small').click();
  // cy.get(':nth-child(1) > :nth-child(1) > .el-button').click();
  cy.get('#lang > :nth-child(3)').click();
  cy.get('#lang > :nth-child(1)').click();
  cy.get('.receivers-container > .el-scrollbar > .el-scrollbar__wrap > .el-scrollbar__view > :nth-child(1) > :nth-child(2)').click();
  // cy.get('[aria-hidden="false"] > div > .el-button--small').click();
  cy.get('.addDomain > span').click();
  cy.get(':nth-child(7) > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').click();
  cy.get(':nth-child(7) > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').clear();
  cy.get(':nth-child(7) > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').type('2');
  cy.get(':nth-child(7) > :nth-child(1) > .el-form-item__content > .el-input > .el-input__inner').click();
  cy.get(':nth-child(7) > :nth-child(2) > .el-form-item__content > .el-input > .el-input__inner').clear();
  cy.get(':nth-child(7) > :nth-child(2) .el-form-item__content > .el-input > .el-input__inner').type('2@q.c');
  cy.get(':nth-child(7) > :nth-child(2) > .el-form-item__content > .el-input > .el-input__inner').clear();
  cy.get(':nth-child(7) > :nth-child(2) > .el-form-item__content > .el-input > .el-input__inner').type('2@q.com');
  cy.get('.el-affix--fixed > :nth-child(2)').click();
  // cy.get('article > :nth-child(4)').click();
  // cy.get('.add-container > .reveiver-container > .el-select > .select-trigger > .el-input > .el-input__inner').click();
  // cy.get('[aria-hidden="false"] > .el-select-dropdown > .el-scrollbar > .el-select-dropdown__wrap > .el-scrollbar__view > :nth-child(2)').click();
  // cy.get('.add-container > .reveiver-container > .el-radio-group > :nth-child(1) > .el-radio__label').click();
  // cy.get('.is-focus > .el-radio__input > .el-radio__original').check();
  // cy.get('.delete-move-button > :nth-child(1) > :nth-child(1) > span').click();
  // cy.get('.add-save-button > :nth-child(2)').click();
  /* ==== End Cypress Studio ==== */
});